### ISSUE TITLE
Suddenly started returning 500 on metrics endpoint

### ISSUE THREAD

**Issue by rmb938** [redpanda-data/kminion#145]
Running kminion 2.1.0. It was working fine and then suddenly it started returning a 500 error on /metrics.

Turned on debug logs and tried upgrading to 2.2.0 but it's still returning 500 and according to the logs everything is returning successful. Any ideas?

Edit: Seemed to fix itself after a rolling restart of the Kafka cluster, still odd there was 0 errors or warnings.

**Comment by weeco** [comment]
Hi @rmb938 ,
are you sure this is returned by KMinion? How long does it take until this is served? What happens if you try to call it's /ready endpoint? 

As you can see here: https://github.com/redpanda-data/kminion/blob/master/main.go#L101 , the Prometheus lib itself is fully in charge of serving the response and I have never seen a 500 error returned there either. I would expect some error log messages at least.

**Comment by rmb938** [comment]
I'm pretty sure, I went into the container and curl'ed it on localhost. In the debug logs I could see it send all the requests to Kafka and right when it stopped logging the 500 was returned, this happened fairly quickly, a second or less.

Unfortunately the issue fixed itself after a Kafka cluster rolling restart... I'll keep an eye out of it happening again and run it against the /ready endpoint.
