### ISSUE TITLE
metric prefix gone in latest version?

### ISSUE THREAD

**Issue by BlackMetalz** [redpanda-data/kminion#225]
I used the old version. Run in k8s pod that has an option for changing metric prefix: (METRICS_PREFIX)
https://github.com/redpanda-data/kminion/blob/ff5320fcf44d830f69a33b88d61dcd484937fa98/README.md

Since I do have multiple clusters, in the past I used to change the metric prefixes for each cluster for easy management.
But right now that option has gone / no effects at all. How i can do it in the current version (redpandadata/kminion:v2.2.3 ) or do you guys have a better way to do it?

**Comment by BlackMetalz** [comment]
LOL. I don't know why you guys don't write a document for environment variables for this or removed :joy: 
I have to read the code to see how it works.

Old version: https://github.com/redpanda-data/kminion/blob/ff5320fcf44d830f69a33b88d61dcd484937fa98/options/options.go#L51

Current version ( 2.2.5 ):
https://github.com/redpanda-data/kminion/blob/master/docs/reference-config.yaml#L162C13-L162C13

So from what I'm finding, it is `EXPORTER_NAMESPACE`

**Comment by weeco** [comment]
@BlackMetalz KMinion adheres to semver releases. You linked a very old commit, which belongs to version 1 (written 4 years ago). Version 2 has been released more than 2 years ago and no breaking changes have been made since then. All configurations are documented here: https://github.com/redpanda-data/kminion/blob/master/docs/reference-config.yaml , the env variable names are auto generated based on the indentation as described in the linked reference config.

**Comment by BlackMetalz** [comment]
> @BlackMetalz KMinion adheres to semver releases. You linked a very old commit, which belongs to version 1 (written 4 years ago). Version 2 has been released more than 2 years ago and no breaking changes have been made since then. All configurations are documented here: https://github.com/redpanda-data/kminion/blob/master/docs/reference-config.yaml , the env variable names are auto generated based on the indentation as described in the linked reference config.

Yep, I understand. That is why I said I have to read in other location, before it was shown in README and I don't need to look at other locations:grin:
